# Generated by Django 4.2.6 on 2023-11-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piloto',
            name='apellido',
            field=models.CharField(max_length=40, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='piloto',
            name='escuderia',
            field=models.CharField(max_length=40, verbose_name='Escuderia'),
        ),
        migrations.AlterField(
            model_name='piloto',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='Nombre'),
        ),
    ]
